server:
  port: ${SERVER_PORT:8083}

spring:
  application:
    name: notification-service

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.basant.*"
        spring.json.use.type.headers: false

kafka:
  topics:
    order-created: order.created
    payment-processed: payment.processed

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    com.basant: DEBUG
